# Generated by Django 3.1.1 on 2020-10-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post_to_be_liked',
            new_name='post_related_like',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user_with_posts',
            new_name='user_related_like',
        ),
        migrations.AlterField(
            model_name='like',
            name='number_of_likes',
            field=models.IntegerField(default=1),
        ),
    ]
