# Generated by Django 3.1.1 on 2020-10-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201003_0747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='number_of_likes',
        ),
        migrations.AddField(
            model_name='like',
            name='like',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='like',
            name='like_text',
            field=models.CharField(default='Empty', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(default='Name_not_known', max_length=100),
        ),
    ]
